### ISSUE TITLE
Unable to join the main network using the snapshot

### ISSUE THREAD

**Issue by YuXiaoCoder** [thetatoken/theta-protocol-ledger#195]
I use the latest client and download the latest snapshot. After verifying the snapshot, the following error is reported. It still fails to delete the data and try again. Who can help me?
theta version: 4.0.0
snapshot: wget -O snapshot `curl -k https://mainnet-data.thetatoken.org/snapshot`
Log:
```bash
[2023-01-13 17:44:32]  INFO [snapshot] Snapshot loaded successfully.
[2023-01-13 17:44:32]  INFO [p2p] Connecting to seed and persisted peers...
[2023-01-13 17:44:32]  WARN [p2p] Failed to retrieve previously persisted peers
[2023-01-13 17:44:32]  INFO [p2p] InboundPeerListener listen routine started, seedPeerOnly set to false
[2023-01-13 17:44:32]  INFO [rpc] RPC server started address=0.0.0.0 port=16888
[2023-01-13 17:44:32]  WARN [reporter] Reporter failed to create request: Post "http://guardian-metrics.thetatoken.org:9000/peers/set": dial tcp 34.220.181.170:9000: connect: connection refused
[2023-01-13 17:44:32]  INFO [p2p] Handshaking with 18.217.234.19:21000...
[2023-01-13 17:44:33]  INFO [p2p] Handshaking with 3.16.9.73:21000...
[2023-01-13 17:44:34]  INFO [p2p] Handshaking with 3.20.109.241:21000...
[2023-01-13 17:44:34]  INFO [p2p] Handshaking with 18.223.165.134:21000...
[2023-01-13 17:44:34]  INFO [p2p] Handshaking with 35.230.172.8:21000...
[2023-01-13 17:44:35]  WARN [p2p] Error during handshake/recv: EOF
[2023-01-13 17:44:35]  WARN [p2p] Failed to handshake with peer, error: EOF
[2023-01-13 17:44:35]  WARN [p2p] Failed to connect to seed peer 18.223.165.134:21000: EOF
[2023-01-13 17:44:35]  WARN [p2p] Error during handshake/recv: read tcp 172.17.0.10:40500->35.230.172.8:21000: read: connection reset by peer
[2023-01-13 17:44:35]  WARN [p2p] Failed to handshake with peer, error: read tcp 172.17.0.10:40500->35.230.172.8:21000: read: connection reset by peer
[2023-01-13 17:44:35]  WARN [p2p] Failed to connect to seed peer 35.230.172.8:21000: read tcp 172.17.0.10:40500->35.230.172.8:21000: read: connection reset by peer
[2023-01-13 17:44:35]  INFO [p2p] Handshaking with 34.83.204.5:21000...                                                                                                   [0/1057]
[2023-01-13 17:44:35]  INFO [p2p] Handshaking with 35.184.232.41:21000...
[2023-01-13 17:44:35]  WARN [p2p] Error during handshake/recv: EOF
[2023-01-13 17:44:35]  WARN [p2p] Failed to handshake with peer, error: EOF
[2023-01-13 17:44:35]  WARN [p2p] Failed to connect to seed peer 35.184.232.41:21000: EOF
[2023-01-13 17:44:42]  WARN [p2p] Error during handshake/recv: read tcp 172.17.0.10:46770->18.217.234.19:21000: i/o timeout
[2023-01-13 17:44:42]  WARN [p2p] Failed to handshake with peer, error: read tcp 172.17.0.10:46770->18.217.234.19:21000: i/o timeout
[2023-01-13 17:44:42]  WARN [p2p] Failed to connect to seed peer 18.217.234.19:21000: read tcp 172.17.0.10:46770->18.217.234.19:21000: i/o timeout
[2023-01-13 17:44:43]  WARN [p2p] Error during handshake/recv: read tcp 172.17.0.10:50698->3.16.9.73:21000: i/o timeout
[2023-01-13 17:44:43]  WARN [p2p] Failed to handshake with peer, error: read tcp 172.17.0.10:50698->3.16.9.73:21000: i/o timeout
[2023-01-13 17:44:43]  WARN [p2p] Failed to connect to seed peer 3.16.9.73:21000: read tcp 172.17.0.10:50698->3.16.9.73:21000: i/o timeout
[2023-01-13 17:44:44] ERROR Failed to create tree store for: 0x064937371b8aa0198a63bc44efd78727b8d79709d2dc8c8bccc95fbc459970d9: missing trie node 064937371b8aa0198a63bc44efd78727b8d79709d2dc8c8bccc95fbc459970d9 (path )
[2023-01-13 17:44:44] PANIC [ledger] Failed to load state for validator pool block.BlockHeader.StateHash=0x064937371b8aa0198a63bc44efd78727b8d79709d2dc8c8bccc95fbc459970d9 block.HCC.BlockHash=0xb1abe2897407d87bb9db5f7cc7a8f87836a294d798a2fae4030d33510edb263e block.Hash=0x6fcc59a60e6cfda51c3207ae9b29a6e760c6b32287dfc0a995ca0b803198f90d block.Height=18762734 block.Status.IsTrusted()=false
panic: (*logrus.Entry) 0xc02dec1030

goroutine 65 [running]:
github.com/sirupsen/logrus.Entry.log({0xc000132000, 0xc02ecc35f0, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x0, ...}, ...)
        /opt/thetamain/goenv/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x289
github.com/sirupsen/logrus.(*Entry).Log(0xc02dec0fc0, 0x0, {0xc00d815040?, 0x0?, 0xffffffffffffffff?})
        /opt/thetamain/goenv/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xa8
github.com/sirupsen/logrus.(*Entry).Panic(0xc0000e6d20?, {0xc00d815040, 0x1, 0x1})
        /opt/thetamain/goenv/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:306 +0x33
github.com/thetatoken/theta/ledger.(*Ledger).GetFinalizedValidatorCandidatePool(0x0?, {0x6f, 0xcc, 0x59, 0xa6, 0xe, 0x6c, 0xfd, 0xa5, 0x1c, ...}, ...)
        /opt/thetamain/core/theta/ledger/ledger.go:137 +0x9e5
github.com/thetatoken/theta/consensus.selectTopStakeHoldersAsValidatorsForBlock({0x1400788?, 0xc018462000?}, {0x16, 0xa8, 0xe4, 0xc1, 0x22, 0xb2, 0xdc, 0x70, ...}, ...)
        /opt/thetamain/core/theta/consensus/validator.go:161 +0x70
github.com/thetatoken/theta/consensus.(*RotatingValidatorManager).GetValidatorSet(0xc00d815330?, {0x16, 0xa8, 0xe4, 0xc1, 0x22, 0xb2, 0xdc, 0x70, 0xba, ...})
        /opt/thetamain/core/theta/consensus/validator.go:128 +0x38
github.com/thetatoken/theta/consensus.(*ConsensusEngine).shouldVoteByID(0x0?, {0xc9, 0x16, 0xa3, 0x5c, 0x7b, 0xc6, 0x16, 0xe2, 0x88, ...}, ...)
        /opt/thetamain/core/theta/consensus/engine.go:827 +0x4d
github.com/thetatoken/theta/consensus.(*ConsensusEngine).shouldVote(0xc018462000, {0x16, 0xa8, 0xe4, 0xc1, 0x22, 0xb2, 0xdc, 0x70, 0xba, ...})
        /opt/thetamain/core/theta/consensus/engine.go:823 +0x8f
github.com/thetatoken/theta/consensus.(*ConsensusEngine).vote(0xc018462000)
        /opt/thetamain/core/theta/consensus/engine.go:835 +0xc6
github.com/thetatoken/theta/consensus.(*ConsensusEngine).mainLoop(0xc018462000)
        /opt/thetamain/core/theta/consensus/engine.go:283 +0x1c7
created by github.com/thetatoken/theta/consensus.(*ConsensusEngine).Start
        /opt/thetamain/core/theta/consensus/engine.go:162 +0x314
```

**Comment by YuXiaoCoder** [comment]
![image](https://user-images.githubusercontent.com/26297513/212297609-bb1e5183-411e-4d4e-9a1f-d1cd3c8eb616.png)

**Comment by YuXiaoCoder** [comment]
I tried the method in this issue: https://github.com/thetatoken/theta-protocol-ledger/issues/189, but still got the same error
